export enum ActionType {
   DELETE_CELL = 'DELETE_CELL',
   UPDATE_CELL = 'UPDATE_CELL',
   INSERT_CELL_BEFORE = 'INSERT_CELL_BEFORE',
   MOVE_CELL = 'MOVE_CELL',
   FETCH_CELL = 'FETCH_CELL',
   ADD_CELL = 'ADD_CELL'
}